# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_related',
            field=models.ManyToManyField(blank=True, related_name='_task_task_related_+', to='ProjectManager.Task'),
        ),
    ]
