# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0002_auto_20170205_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_members',
            field=models.ManyToManyField(blank=True, to='ProjectManager.Member'),
        ),
    ]
