# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0003_auto_20170205_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='progress_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Member'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Task'),
        ),
    ]
