# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0004_auto_20170212_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_gauge',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
