# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0006_task_task_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_department',
            field=models.CharField(choices=[('project manager', 'project manager'), ('team manager', 'team manager'), ('freelancer', 'freelancer'), ('backend programmer', 'backend programmer'), ('frontend programmer', 'frontend programmer'), ('undesignated', 'undesignated')], default='undesignated', max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_name',
            field=models.CharField(default='member_', help_text='project member nickname', max_length=100),
        ),
    ]
