# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0010_progress_progress_closed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='progress_gauge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_progress',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
    ]
