# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-19 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectManager', '0011_auto_20170219_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
