# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datafile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('filepath', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('finished', 'finished')], max_length=30)),
                ('job_priority', models.IntegerField(default=1)),
                ('job_name', models.CharField(max_length=50)),
                ('job_submitter', models.CharField(max_length=50)),
                ('job_dataset_size', models.IntegerField(default=0)),
                ('job_started_at', models.DateTimeField(auto_now=True)),
                ('job_deadline', models.DateTimeField(blank=True, null=True)),
                ('job_completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
