# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0002_datafile_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-pk',)},
        ),
    ]
