# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 14:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0004_auto_20170205_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_submitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
