# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0005_auto_20170205_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_submitter',
        ),
    ]
