# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 12:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Analyzer', '0006_remove_job_job_submitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_submitter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
