# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 10:43
from __future__ import unicode_literals

import Analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0008_auto_20170416_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='filepath',
            field=models.FileField(blank=True, null=True, upload_to=Analyzer.models.get_user_uploadfile_folder),
        ),
    ]
