# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0009_datafile_filepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('finished', 'finished')], default='pending', max_length=30),
        ),
    ]
