# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0010_auto_20170517_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_solver',
            field=models.CharField(choices=[('Testing', 'Testing'), ('DeepDream', 'DeepDream'), ('StyleTransfer', 'StyleTransfer')], default='Testing', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_submitter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
