# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 09:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0011_auto_20170518_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='fileowner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_solver',
            field=models.CharField(choices=[('Testing', 'Testing'), ('DeepDream', 'DeepDream'), ('StyleTransfer', 'StyleTransfer'), ('mlsolver', 'mlsolver')], default='Testing', max_length=30),
        ),
    ]
