# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelfield_1', models.CharField(max_length=100)),
                ('modelfield_2', models.IntegerField()),
                ('modelfield_3', models.BooleanField()),
                ('modelfield_4_1', models.DateField(auto_now_add=True)),
                ('modelfield_4_2', models.DateField()),
                ('modelfield_5', models.DecimalField(decimal_places=5, max_digits=5)),
                ('modelfield_6', models.FileField(upload_to='')),
                ('modelfield_7', models.EmailField(max_length=254)),
            ],
        ),
    ]
