# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_block', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemodel',
            name='modelfield_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='modelfield_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='modelfield_4_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='modelfield_5',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='modelfield_6',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='samplemodel',
            name='modelfield_7',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
