# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessagereceived',
            old_name='targetuser',
            new_name='fromuser',
        ),
        migrations.RenameField(
            model_name='usermessagesent',
            old_name='fromuser',
            new_name='touser',
        ),
        migrations.AddField(
            model_name='usermessagesent',
            name='sent',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserMessageReceived'),
            preserve_default=False,
        ),
    ]
