# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_auto_20170206_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessagesent',
            name='sent',
        ),
        migrations.AddField(
            model_name='usermessagereceived',
            name='received',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserMessageSent'),
            preserve_default=False,
        ),
    ]
