# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_auto_20170206_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fromuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromuser', to='UserProfile.UserProfile')),
                ('received', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserMessageSent')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='touser', to='UserProfile.UserProfile')),
            ],
        ),
    ]
