# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0006_auto_20170206_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_facebook',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_location',
            field=models.CharField(default='Seoul', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
