# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0007_auto_20170208_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo_path',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
