# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0010_auto_20170209_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projectinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Member'),
        ),
    ]
