# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-13 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0013_auto_20170210_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projectinfo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Member'),
        ),
    ]
