# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 14:54
from __future__ import unicode_literals

import UserProfile.views
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectManager', '0008_project_project_status'),
        ('UserProfile', '0014_auto_20170213_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_path', models.FileField(upload_to=UserProfile.views.get_user_uploadfile_folder)),
                ('file_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Project')),
                ('file_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Task')),
            ],
        ),
    ]
