# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0015_userfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='projectinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ProjectManager.Member'),
        ),
    ]
