# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firstmodel',
            fields=[
                ('modelfield4_2', models.ImageField(auto_created=True, upload_to='%yy/%mm/%dd/')),
                ('modelfield0', models.AutoField(primary_key=True, serialize=False)),
                ('modelfield1_1', models.IntegerField()),
                ('modelfield1_2', models.BigIntegerField(unique=True, verbose_name='64bit integer')),
                ('modelfield1_3', models.PositiveIntegerField(blank=True)),
                ('modelfield1_4', models.SmallIntegerField(verbose_name='16bit integer')),
                ('modelfield1_5', models.FloatField(choices=[(1.1, 'first'), (2.1, 'second'), (3.1, 'third')])),
                ('modelfield1_6', models.DecimalField(decimal_places=4, max_digits=10)),
                ('modelfield2', models.BinaryField()),
                ('modelfield3_1', models.CharField(default='hello', max_length=100)),
                ('modelfield3_2', models.EmailField(max_length=254)),
                ('modelfield3_3', models.URLField()),
                ('modelfield3_4', models.TextField()),
                ('modelfield4_1', models.FileField(upload_to='')),
                ('modelfield5_1', models.DateField(auto_now=True)),
                ('modelfield5_2', models.DateTimeField(auto_now_add=True)),
                ('modelfield6', models.GenericIPAddressField()),
                ('modelfield7', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ManyToManyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelfield0', models.ManyToManyField(to='model_block.firstmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ManyToOneBefore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelfield0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_block.firstmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OneToManyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelfield0', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model_block.firstmodel')),
            ],
        ),
        migrations.CreateModel(
            name='OneToOneModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelfield0', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model_block.firstmodel')),
            ],
        ),
    ]
