# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_block', '0002_auto_20161206_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstmodel',
            name='modelfield1_1',
            field=models.IntegerField(default=1),
        ),
    ]
