# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-21 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model_block', '0003_auto_20161207_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstmodel',
            options={'get_latest_by': 'modelfield5_1', 'ordering': ['-modelfield5_1']},
        ),
    ]
